#!/bin/sh

set -e

netlify --version

if [ "$NETLIFY_AUTH_TOKEN" = '' ]; then
  echo 'NETLIFY_AUTH_TOKEN not set. Exiting.'
  exit 1
fi

if [ "$BUILDKITE_BRANCH" = 'main' ]; then
  echo 'Deploying to production.'
  netlify deploy --prod
else
  echo 'Deploying to draft site.'
  netlify deploy
fi
